trigger:
  - main

pool: Roboshop-workstation

variables:
  COMPONENT: user

resources:
  repositories:
    - repository: templates
      type: github
      name: dailypractice-all/roboshop-azure-devops-templates
      endpoint: dailypractice-all

stages:
- template: nodejs.yml@templates